# Generated by Django 4.2 on 2023-06-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_orm', '0003_remove_class_students_remove_class_teacher_teaches_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
    ]
