# Generated by Django 4.2 on 2023-06-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_orm', '0004_alter_teacher_managers_remove_teacher_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
