version: '3.9'
services:
  web:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: School
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sadnightdynamite    
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: